# NumPy em Python

Este notebook apresenta uma introdução completa à biblioteca **NumPy**, utilizada para computação numérica e manipulação eficiente de arrays.

Você aprenderá:
- O que é o NumPy
- Arrays (`ndarray`)
- Criação de arrays
- Indexação e fatiamento
- Operações matemáticas
- Broadcasting
- Estatísticas
- Álgebra linear
- Geração de números aleatórios
- Boas práticas


## 1. O que é o NumPy?

NumPy é a principal biblioteca para computação numérica em Python. Seu objeto principal é o `ndarray`, que é mais eficiente que listas para operações matemáticas.

In [1]:
import numpy as np

print(np.__version__)

2.4.5


## 2. Criando arrays

Arrays podem ser criados a partir de listas ou funções do NumPy.

In [2]:
a = np.array([1,2,3,4])
b = np.zeros(5)
c = np.ones((2,3))
d = np.arange(0,10,2)

print(a)
print(b)
print(c)
print(d)

[1 2 3 4]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


## 3. Propriedades

Descubra dimensões, formato e tipo dos dados.

In [3]:
matriz = np.array([[1,2,3],[4,5,6]])

print(matriz.shape)
print(matriz.ndim)
print(matriz.size)
print(matriz.dtype)

(2, 3)
2
6
int64


## 4. Indexação e fatiamento

Acesse elementos, linhas, colunas e subconjuntos.

In [4]:
arr = np.array([[10,20,30],[40,50,60]])

print(arr[0,1])
print(arr[:,0])
print(arr[1,:])
print(arr[:,1:])

20
[10 40]
[40 50 60]
[[20 30]
 [50 60]]


## 5. Operações matemáticas

As operações são vetorizadas.

In [5]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


## 6. Broadcasting

Permite operações entre arrays de tamanhos compatíveis.

In [6]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat + 10)

[[11 12 13]
 [14 15 16]]


## 7. Funções estatísticas

Calcule estatísticas rapidamente.

In [7]:
dados = np.array([10,20,30,40,50])

print(np.mean(dados))
print(np.median(dados))
print(np.std(dados))
print(np.min(dados))
print(np.max(dados))
print(np.sum(dados))

30.0
30.0
14.142135623730951
10
50
150


## 8. Remodelando arrays

Use `reshape()` para alterar o formato.

In [8]:
v = np.arange(12)
m = v.reshape(3,4)

print(v)
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 9. Álgebra linear

NumPy possui diversas funções para álgebra linear.

In [9]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A @ B)
print(np.linalg.det(A))
print(np.linalg.inv(A))

[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


## 10. Números aleatórios

Gere amostras aleatórias.

In [10]:
np.random.seed(42)

print(np.random.rand(5))
print(np.random.randint(1,11,size=5))
print(np.random.normal(0,1,5))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[3 7 8 5 4]
[ 0.39257975 -0.92918467  0.07983181 -0.1595165   0.02222183]


## 11. Boas práticas

- Prefira operações vetorizadas.
- Evite loops quando possível.
- Utilize arrays homogêneos.
- Aproveite funções do módulo `numpy.linalg` e `numpy.random`.


In [11]:
dados = np.arange(1,6)
print(dados * 2)
print(np.sqrt(dados))

[ 2  4  6  8 10]
[1.         1.41421356 1.73205081 2.         2.23606798]


# Exercícios

1. Crie um array com os números de 1 a 20.
2. Crie uma matriz 3×3 preenchida com zeros.
3. Calcule a média e o desvio padrão de um array.
4. Multiplique dois arrays elemento a elemento.
5. Utilize `reshape()` para transformar um vetor em matriz.
6. Gere 10 números inteiros aleatórios entre 1 e 100.
7. Calcule o produto matricial entre duas matrizes.
8. Encontre o maior e o menor elemento de um array.


# Resumo

Neste notebook você aprendeu:

- Instalação e importação do NumPy
- Criação de arrays
- Propriedades dos arrays
- Indexação e fatiamento
- Operações matemáticas vetorizadas
- Broadcasting
- Estatísticas
- Remodelagem de arrays
- Álgebra linear
- Geração de números aleatórios
- Boas práticas

O NumPy é a base do ecossistema de ciência de dados em Python e é amplamente utilizado em bibliotecas como Pandas, SciPy, Scikit-learn, TensorFlow e PyTorch.
